name: mysql

services:
  mysql:
    image: mysql:8.0.35
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - C:\software\mysql\data:/var/lib/mysql
